select A_ASSETLOCUSERCUST.EAUDITUSERNAME, A_ASSETLOCUSERCUST.EAUDITTYPE, 
  A_ASSETLOCUSERCUST.EAUDITTYPE, A_ASSETLOCUSERCUST.EAUDITTIMESTAMP, 
  A_ASSETLOCUSERCUST.ASSETNUM, A_ASSETLOCUSERCUST.PERSONID,
  A_ASSETLOCUSERCUST.ISUSER, A_ASSETLOCUSERCUST.ISCUSTODIAN, 
  A_ASSETLOCUSERCUST.ISPRIMARY
from A_ASSETLOCUSERCUST
order by EAUDITTIMESTAMP desc;

select a_asset.EAUDITUSERNAME, a_asset.EAUDITTYPE, a_asset.EAUDITTYPE, 
  a_asset.EAUDITTIMESTAMP, a_asset.ASSETNUM, a_asset.ASSETTAG, a_asset.SERIALNUM  
from a_asset
order by EAUDITTIMESTAMP desc;