

select distinct PERSON.SUPERVISOR, assetusercust.PERSONID, PERSON.DISPLAYNAME
  , REGEXP_REPLACE(PERSON.DISPLAYNAME, '(.+),\s+(.+)','\2 \1') REGEXP_NAME, PERSON.STATUS PERSONSTATUS
  , PERSON.LOCATION, PERSON.TITLE
--  , ASSETUSERCUST.ASSETNUM, ASSET.ASSETTAG
  , PHYSCOUNT.PHYSCOUNT, VIRTCOUNT.VDICOUNT
--  , (select max(LOGINTRACKING.ATTEMPTDATE)
--      from LOGINTRACKING 
--      where LOGINTRACKING.userid = ASSETUSERCUST.PERSONID 
--        and LOGINTRACKING.ATTEMPTRESULT = 'LOGIN'
--      ) LOGINDATE
from ASSETUSERCUST
  join PERSON on PERSON.PERSONID = ASSETUSERCUST.PERSONID
--  join asset on ASSETUSERCUST.ASSETNUM = ASSET.ASSETNUM
  join (select ASSETUSERCUST.PERSONID, ASSETUSERCUST.ISUSER, ASSETUSERCUST.ISCUSTODIAN, COUNT(*) VDICOUNT 
        from ASSETUSERCUST
          join ASSET on ASSETUSERCUST.ASSETNUM = ASSET.ASSETNUM
        where ASSET.CLASSSTRUCTUREID = '1328'
          and ASSETUSERCUST.ISUSER = '1'
          and ASSET.STATUS in ('DEPLOYED', 'IN STOCK', 'REPAIR')
        group by ASSETUSERCUST.PERSONID, ASSETUSERCUST.ISUSER, ASSETUSERCUST.ISCUSTODIAN) VIRTCOUNT on VIRTCOUNT.PERSONID = ASSETUSERCUST.PERSONID
  left join (select ASSETUSERCUST.PERSONID, ASSETUSERCUST.ISUSER, ASSETUSERCUST.ISCUSTODIAN, COUNT(*) PHYSCOUNT 
        from ASSETUSERCUST
          join ASSET on ASSETUSERCUST.ASSETNUM = ASSET.ASSETNUM
        where (ASSET.CLASSSTRUCTUREID in ('1238', '1243')
          or (ASSET.CLASSSTRUCTUREID = '1241' and ASSETUSERCUST.ASSETNUM in (select ASSETNUM from ASSET where UPPER(EX_MODEL) like '%SURFACE%')))
          and ASSETUSERCUST.ISUSER = '1'
          and ASSET.STATUS in ('DEPLOYED', 'IN STOCK', 'REPAIR')
        group by ASSETUSERCUST.PERSONID, ASSETUSERCUST.ISUSER, ASSETUSERCUST.ISCUSTODIAN) PHYSCOUNT on PHYSCOUNT.PERSONID = ASSETUSERCUST.PERSONID
  where PERSON.STATUS = 'ACTIVE'
order by PERSON.SUPERVISOR, ASSETUSERCUST.PERSONID
;


select * from classstructure where classstructureid in ('1238', '1243', '1328');



select ATTEMPTDATE, ATTEMPTRESULT, name, CLIENTHOST, CLIENTADDR 
from MAXIMO.LOGINTRACKING
where USERID in ('RSAN PED')
  and ATTEMPTRESULT = 'LOGIN'
order by ATTEMPTDATE desc;