
select MAXATTRIBUTECFG.OBJECTNAME, MAXATTRIBUTECFG.ATTRIBUTENAME
from MAXATTRIBUTECFG
  join MAXTABLE on MAXATTRIBUTECFG.OBJECTNAME = MAXTABLE.TABLENAME
where MAXATTRIBUTECFG.SAMEASATTRIBUTE in ('PERSONGROUP')
--  and MAXTABLE.ISAUDITTABLE = '0'
  and MAXATTRIBUTECFG.PERSISTENT = '1'
order by MAXATTRIBUTECFG.OBJECTNAME, MAXATTRIBUTECFG.ATTRIBUTENAME;
