select LOCATIONS.LOCATION, ASSET.ASSETNUM, ASSET.ASSETTAG, CLASSSTRUCTURE.CLASSIFICATIONID, PERSON.PERSONID
from LOCATIONS
  left join ASSET on LOCATIONS.LOCATION = ASSET.LOCATION
  join CLASSSTRUCTURE on CLASSSTRUCTURE.CLASSSTRUCTUREID = ASSET.CLASSSTRUCTUREID
  left join PERSON on PERSON.LOCATION = LOCATIONS.LOCATION
where LOCATIONS.LOCATION like ('[[LOCATION]]');